name: Website Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Build and Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Website Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy Website
        uses: actions/deploy-pages@v4
